/**
 * Copyright(c)2013,Wozlla,www.wozlla.com
 * Version: 1.0
 * Author: Peter Zhang
 * Date: 2013-03-27
 * Description: UI资源
 */
var ui_resources = {
	mainScene: [{
		name: "cr_attribute_bg",
		type: "image",
		src: "res/ui/layout/c/cr_attribute_bg.png"
	}, {
		name: "cr_buff_font",
		type: "image",
		src: "res/ui/font/zh_CN/cr_buff_font.png"
	}, {
		name: "cr_exp",
		type: "image",
		src: "res/ui/layout/c/cr_exp.png"
	}, {
		name: "cr_level_bg",
		type: "image",
		src: "res/ui/layout/c/cr_level_bg.png"
	}, {
		name: "ft_arrowdown_bg",
		type: "image",
		src: "res/ui/layout/c/ft_arrowdown_bg.png"
	}, {
		name: "ft_arrowup_bg",
		type: "image",
		src: "res/ui/layout/c/ft_arrowup_bg.png"
	}, {
		name: "ft_attack",
		type: "image",
		src: "res/ui/layout/c/ft_attack.png"
	}, {
		name: "ft_down_bg",
		type: "image",
		src: "res/ui/layout/c/ft_down_bg.png"
	}, {
		name: "ft_position",
		type: "image",
		src: "res/ui/layout/c/ft_position.png"
	}, {
		name: "ft_up_bg",
		type: "image",
		src: "res/ui/layout/c/ft_up_bg.png"
	}, {
		name: "ft_use",
		type: "image",
		src: "res/ui/layout/c/ft_use.png"
	}, {
		name: "ft_windowleft_bg",
		type: "image",
		src: "res/ui/layout/c/ft_windowleft_bg.png"
	}, {
		name: "ft_windowright_bg",
		type: "image",
		src: "res/ui/layout/c/ft_windowright_bg.png"
	}, {
		name: "lock",
		type: "image",
		src: "res/ui/layout/c/lock.png"
	}, {
		name: "mainPlayer_bg",
		type: "image",
		src: "res/ui/layout/c/mainPlayer_bg.png"
	}, {
		name: "pb_up",
		type: "image",
		src: "res/ui/layout/c/pb_up.png"
	}, {
		name: "pb_up_h",
		type: "image",
		src: "res/ui/layout/c/pb_up_h.png"
	}, {
		name: "popupbox_bg1",
		type: "image",
		src: "res/ui/layout/c/popupbox_bg1.png"
	}, {
		name: "popupbox_bg2",
		type: "image",
		src: "res/ui/layout/c/popupbox_bg2.png"
	}, {
		name: "rightTop_bg",
		type: "image",
		src: "res/ui/layout/c/rightTop_bg.png"
	}, {
		name: "rst_1_icon",
		type: "image",
		src: "res/ui/layout/c/rst_1_icon.png"
	}, {
		name: "rst_bg_icon",
		type: "image",
		src: "res/ui/layout/c/rst_bg_icon.png"
	}, {
		name: "shop_line",
		type: "image",
		src: "res/ui/layout/c/shop_line.png"
	}, {
		name: "skill_ph_bg",
		type: "image",
		src: "res/ui/layout/c/skill_ph_bg.png"
	}, {
		name: "st_adb_leve_bg",
		type: "image",
		src: "res/ui/layout/c/st_adb_leve_bg.png"
	}, {
		name: "st_sbd_chose",
		type: "image",
		src: "res/ui/layout/c/st_sbd_chose.png"
	}, {
		name: "st_tfm_boat_bg",
		type: "image",
		src: "res/ui/layout/c/st_tfm_boat_bg.png"
	}, {
		name: "sy_abd_alone_bg",
		type: "image",
		src: "res/ui/layout/c/sy_abd_alone_bg.png"
	}, {
		name: "sy_abd_double_bg",
		type: "image",
		src: "res/ui/layout/c/sy_abd_double_bg.png"
	}, {
		name: "tips",
		type: "image",
		src: "res/ui/layout/c/tips.png"
	}, {
		name: "window_bg",
		type: "image",
		src: "res/ui/layout/c/window_bg.png"
	}, {
		name: "add",
		type: "image",
		src: "res/ui/btn/add.png"
	}, {
		name: "add_h",
		type: "image",
		src: "res/ui/btn/add_h.png"
	}, {
		name: "assistant",
		type: "image",
		src: "res/ui/btn/assistant.png"
	}, {
		name: "assistant_h",
		type: "image",
		src: "res/ui/btn/assistant_h.png"
	}, {
		name: "btn_bg",
		type: "image",
		src: "res/ui/btn/btn_bg.png"
	}, {
		name: "btn_bg_disable",
		type: "image",
		src: "res/ui/btn/btn_bg_disable.png"
	}, {
		name: "btn_bg_h",
		type: "image",
		src: "res/ui/btn/btn_bg_h.png"
	}, {
		name: "btn_tfm_bg",
		type: "image",
		src: "res/ui/btn/btn_tfm_bg.png"
	}, {
		name: "btn_tfm_bg_h",
		type: "image",
		src: "res/ui/btn/btn_tfm_bg_h.png"
	}, {
		name: "casino_btn",
		type: "image",
		src: "res/ui/btn/casino_btn.png"
	}, {
		name: "casino_btn_h",
		type: "image",
		src: "res/ui/btn/casino_btn_h.png"
	}, {
		name: "chat_arrow",
		type: "image",
		src: "res/ui/btn/chat_arrow.png"
	}, {
		name: "chat_icon",
		type: "image",
		src: "res/ui/btn/chat_icon.png"
	}, {
		name: "chat_submit",
		type: "image",
		src: "res/ui/btn/chat_submit.png"
	}, {
		name: "chat_submit_h",
		type: "image",
		src: "res/ui/btn/chat_submit_h.png"
	}, {
		name: "close",
		type: "image",
		src: "res/ui/btn/close.png"
	}, {
		name: "close_h",
		type: "image",
		src: "res/ui/btn/close_h.png"
	}, {
		name: "map",
		type: "image",
		src: "res/ui/btn/map.png"
	}, {
		name: "map_h",
		type: "image",
		src: "res/ui/btn/map_h.png"
	}, {
		name: "menu",
		type: "image",
		src: "res/ui/btn/menu.png"
	}, {
		name: "menu_h",
		type: "image",
		src: "res/ui/btn/menu_h.png"
	}, {
		name: "menuicon",
		type: "image",
		src: "res/ui/btn/menuicon.png"
	}, {
		name: "nearby_tab_btn",
		type: "image",
		src: "res/ui/btn/nearby_tab_btn.png"
	}, {
		name: "nearby_tab_btn_h",
		type: "image",
		src: "res/ui/btn/nearby_tab_btn_h.png"
	}, {
		name: "pb_up",
		type: "image",
		src: "res/ui/btn/pb_up.png"
	}, {
		name: "pb_up_h",
		type: "image",
		src: "res/ui/btn/pb_up_h.png"
	}, {
		name: "popupbox_btn",
		type: "image",
		src: "res/ui/btn/popupbox_btn.png"
	}, {
		name: "postMessage",
		type: "image",
		src: "res/ui/btn/postMessage.png"
	}, {
		name: "postMessage_h",
		type: "image",
		src: "res/ui/btn/postMessage_h.png"
	}, {
		name: "recharge",
		type: "image",
		src: "res/ui/btn/recharge.png"
	}, {
		name: "recharge_h",
		type: "image",
		src: "res/ui/btn/recharge_h.png"
	}, {
		name: "shop_tag_bg",
		type: "image",
		src: "res/ui/btn/shop_tag_bg.png"
	}, {
		name: "shop_tag_h_bg",
		type: "image",
		src: "res/ui/btn/shop_tag_h_bg.png"
	}, {
		name: "tab_left_bg",
		type: "image",
		src: "res/ui/btn/tab_left_bg.png"
	}, {
		name: "tab_left_bg_h",
		type: "image",
		src: "res/ui/btn/tab_left_bg_h.png"
	}, {
		name: "tab_right_bg",
		type: "image",
		src: "res/ui/btn/tab_right_bg.png"
	}, {
		name: "tab_right_bg_h",
		type: "image",
		src: "res/ui/btn/tab_right_bg_h.png"
	}, {
		name: "task_accept_btn",
		type: "image",
		src: "res/ui/btn/task_accept_btn.png"
	}, {
		name: "task_disable_btn",
		type: "image",
		src: "res/ui/btn/task_disable_btn.png"
	}, {
		name: "task_submit_btn",
		type: "image",
		src: "res/ui/btn/task_submit_btn.png"
	}, {
		name: "task_tab_btn",
		type: "image",
		src: "res/ui/btn/task_tab_btn.png"
	}, {
		name: "task_tab_btn_h",
		type: "image",
		src: "res/ui/btn/task_tab_btn_h.png"
	}],
	fightScene: [{
		name: "fi_mark_bg",
		type: "image",
		src: "res/ui/layout/f/fi_mark_bg.png"
	}, {
		name: "fi_top_bg",
		type: "image",
		src: "res/ui/layout/f/fi_top_bg.png"
	}, {
		name: "res_bg",
		type: "image",
		src: "res/ui/layout/f/res_bg.png"
	}, {
		name: "res_lose_tab",
		type: "image",
		src: "res/ui/layout/f/res_lose_tab.png"
	}, {
		name: "res_star_bg",
		type: "image",
		src: "res/ui/layout/f/res_star_bg.png"
	}, {
		name: "res_starwin_bg",
		type: "image",
		src: "res/ui/layout/f/res_starwin_bg.png"
	}, {
		name: "res_win_tab",
		type: "image",
		src: "res/ui/layout/f/res_win_tab.png"
	}],
	characterWindow: [{
		name: "0_buff",
		type: "image",
		src: "res/ui/ci/0/0_buff.png"
	}, {
		name: "0_bust",
		type: "image",
		src: "res/ui/ci/0/0_bust.png"
	}, {
		name: "0_photo",
		type: "image",
		src: "res/ui/ci/0/0_photo.png"
	}, {
		name: "0_tab",
		type: "image",
		src: "res/ui/ci/0/0_tab.png"
	}, {
		name: "0_tab_h",
		type: "image",
		src: "res/ui/ci/0/0_tab_h.png"
	}],
	casinoScene: [{
		name: "casino_font_bg",
		type: "image",
		src: "res/ui/layout/g/casino_font_bg.png"
	}, {
		name: "casino_photoleft_bg",
		type: "image",
		src: "res/ui/layout/g/casino_photoleft_bg.png"
	}, {
		name: "casino_photoright_bg",
		type: "image",
		src: "res/ui/layout/g/casino_photoright_bg.png"
	}, {
		name: "dice",
		type: "image",
		src: "res/ui/layout/g/dice.png"
	}]
};